image: drupalpod/drupalpod-gitpod-base:20230922

# DDEV and composer are running as part of the prebuild
# when starting a workspace all docker images are ready
tasks:
  - init: |
      ddev config global --instrumentation-opt-in=false
      time ddev start
      time ddev composer install
    command: |
      ddev config global --instrumentation-opt-in=false
      time ddev start
      ddev describe
      gp preview $(gp url 8080)

ports:
  # Used by JS projects
  - port: 3000
    onOpen: ignore
  # Used by DDEV - local db clients
  - port: 3306
    name: Database
    description: Access for local database clients
    onOpen: ignore
  # Used by JS projects
  - port: 5000
    onOpen: ignore
  # Used by MailHog
  - port: 8027
    name: MailHog
    description: MailHog
    onOpen: ignore
  # Used by phpMyAdmin
  - port: 8036
    name: phpMyAdmin
    description: phpMyAdmin
    onOpen: ignore
  # Direct-connect DDEV-webserver port that is the main port
  - port: 8080
    name: website
    description: website
    onOpen: ignore
  # Ignore host https port
  - port: 8443
    name: (not used)
    description: host https port
    onOpen: ignore
  # xdebug port
  - port: 9003
    name: xdebug
    description: xdebug
    onOpen: ignore

